# Persist SQLite DB across restarts - data stored in ./data on host
version: "3.9"

services:
  api:
    build: .
    container_name: cost-guardian-api
    env_file: .env
    environment:
      - DB_FILENAME=usage_log.sqlite
    command: >
      gunicorn app:app
      -w 4
      -k gthread
      --threads 2
      -b 0.0.0.0:5001
      --timeout 30
      --graceful-timeout 30
      --keep-alive 5
      --max-requests 2000
      --max-requests-jitter 200
      --forwarded-allow-ips="*"
      --access-logfile -
      --error-logfile -
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data  # Persistent database storage
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:5001/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

