# Persist SQLite DB across restarts - data stored in ./data on host
version: "3.9"

services:
  api:
    build: .
    container_name: cost-guardian-api
    env_file: .env
    environment:
      - DB_FILENAME=usage_log.sqlite
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data  # Persistent database storage
    # Optional: rely on Dockerfile's HEALTHCHECK, so omit here
    restart: unless-stopped

  # Worker service (for development/testing only)
  # Production deployments should disable this and use client-push ingestion
  worker:
    build: .
    container_name: cost-guardian-worker
    env_file: .env
    environment:
      - DB_FILENAME=usage_log.sqlite
    command: ["python", "worker.py"]
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ./data:/app/data  # Persistent database storage
    restart: unless-stopped
