version: "3.9"

services:
  api:
    build: .
    container_name: cost-guardian-api
    env_file: .env
    environment:
      - DB_FILENAME=data/cost_guardian.db
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data
    # Optional: rely on Dockerfile's HEALTHCHECK, so omit here
    restart: unless-stopped

  worker:
    build: .
    container_name: cost-guardian-worker
    env_file: .env
    environment:
      - DB_FILENAME=data/cost_guardian.db
    command: ["python", "worker.py"]
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    restart: unless-stopped
